version: "3.8"

services:
  ulm-trmnl:
    build:
      context: .
    environment:
      - TRASH_BEZIRK=YOUR_DISTRICT
      - TRASH_WEBHOOK=https://example.com/webhook
      - TRASH_INTERVAL=86400
    restart: unless-stopped
