version: "3.8"

services:
  ulm-trmnl:
    build:
      context: .
    environment:
      - PYTHONUNBUFFERED=1
      - TRASH_BEZIRK
      - TRASH_WEBHOOK
      - TRASH_INTERVAL
    restart: unless-stopped
